name: Main

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t dockerzvip/s3fs-samba:${{ github.sha }} .
          docker tag dockerzvip/s3fs-samba:${{ github.sha }} dockerzvip/s3fs-samba:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push dockerzvip/s3fs-samba:latest
          docker push dockerzvip/s3fs-samba:${{ github.sha }}
